name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies + SFML & OpenGL Dependencies
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype6-dev libgl-dev libglx-dev libopengl-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install -y --no-install-recommends valgrind
